id: PAD60DB5D
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN10210
  title: རྣལ་འབྱོར་བླ་མེད་ཀྱི་སྒྲུབ་ཐབས་དང་བསྐྱེད་རིམ་གྱི་ཁྲིད་ཡིག་ཁག
  volumes:
    30ebafcb77be4a0fbe1c1d5346efcae7:
      image_group_id: I3CN10212
      title: ''
      base_file: v001.txt
  author: ''
